#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "list.h"
#include "grid.h"
#include "navigation.h"

task main()
{
	int goals_found;
	int position[2];
	int orientation;
	char grid[GRID_NROWS*GRID_NCOLS];

	// Posicao inicial do robo
	position[0] = 4;
	position[1] = 0;

	// Orientacao inicial do robo
	orientation = NORTE;

	// Inicializando variaveis
	init_grid(grid, 'f');
	goals_found = 0;
	set_grid(grid,2,0,'g'); // GOAL
	set_grid(grid,position[0],position[1],'v'); // Posicao inicial marcada como visitada
	
	init_robot();
	check_surrounding(position, &orientation);
	move_straight(3, orientation, position);
	check_surrounding(position, &orientation);	
	move_straight(1, orientation, position);
	turn(ESQUERDA, &orientation);
	check_surrounding(position, &orientation);
	move_straight(2, orientation, position);
	turn(ESQUERDA, &orientation);
	move_straight(1, orientation, position);
	check_surrounding(position, &orientation);
	move_straight(3, orientation, position);

	return;
}
